<a href="https://colab.research.google.com/github/Eshumael86/neural-network-challenge-2/blob/main/attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [19]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [10]:
print(attrition_df.columns)

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')


In [11]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'YearsSinceLastPromotion', 'OverTime', 'DistanceFromHome', 'Education', 'YearsAtCompany', 'WorkLifeBalance', 'StockOptionLevel', 'NumCompaniesWorked', 'JobSatisfaction',]
# Create X_df using your selected columns
x_df = attrition_df[x_columns]
x_df.head()

# Show the data types for X_df
x_df.dtypes


Age                         int64
YearsSinceLastPromotion     int64
OverTime                   object
DistanceFromHome            int64
Education                   int64
YearsAtCompany              int64
WorkLifeBalance             int64
StockOptionLevel            int64
NumCompaniesWorked          int64
JobSatisfaction             int64
dtype: object

In [12]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
m_train, m_test, y_train, y_test = train_test_split(x_df, y_df, random_state=1)

In [15]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
x_df = pd.get_dummies(x_df)
x_df.head()

Age  YearsSinceLastPromotion  DistanceFromHome  Education  YearsAtCompany  \
0   41                        0                 1          2               6   
1   49                        1                 8          1              10   
2   37                        0                 2          2               0   
3   33                        3                 3          4               8   
4   27                        2                 2          1               2   

   WorkLifeBalance  StockOptionLevel  NumCompaniesWorked  JobSatisfaction  \
0                1                 0                   8                4   
1                3                 1                   1                2   
2                3                 0                   6                3   
3                3                 0                   1                3   
4                3                 1                   9                2   

   OverTime_No  OverTime_Yes  
0        False          True  
1         True         False  
2        False          True  
3        False          True  
4         True         False

In [23]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(x_df)
# Transform the training and testing data
x_df = scaler.transform(x_df)
# Scale the training and testing data
x_df = scaler.transform(x_df)

In [30]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
Department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
Department_encoder.fit(y_df[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
Department_train = Department_encoder.transform(y_train[['Department']])
Department_test = Department_encoder.transform(y_test[['Department']])

Department_train
Department_test

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [31]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
attrition_encoder.fit(y_df[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
attrition_train = attrition_encoder.transform(y_train[['Attrition']])
attrition_test = attrition_encoder.transform(y_test[['Attrition']])

attrition_train
attrition_test


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

## Part 2: Create, Compile, and Train the Model

In [32]:
# Find the number of columns in the X training data.
x_df.shape[1]
# Create the input layer
input_layer = layers.Input(shape=(x_df.shape[1],))

# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(units=32, activation='relu')(shared_layer1)

In [34]:
# Create a branch for Department
# with a hidden layer and an output layer
department_layer1 = layers.Dense(units=32, activation='relu')(shared_layer2)
department_output = layers.Dense(units=2, activation='softmax')(department_layer1)
# Create the hidden layer
hidden_layer = layers.Dense(units=64, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=2, activation='softmax')(hidden_layer)

In [35]:
# Create a branch for Attrition
# with a hidden layer and an output layer
attrition_layer1 = layers.Dense(units=32, activation='relu')(shared_layer2)
attrition_output = layers.Dense(units=2, activation='softmax')(attrition_layer1)
# Create the hidden layer
hidden_layer = layers.Dense(units=64, activation='relu')(shared_layer2)

# Create the output layer
output_layer = layers.Dense(units=2, activation='softmax')(hidden_layer)

In [36]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 11)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense (Dense)             │ (None, 64)             │            768 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_1 (Dense)           │ (None, 32)             │          2,080 │ dense[0][0]            │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_6 (Dense)           │ (None, 32)             │          1,056 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_10 (Dense)          │ (None, 32)             │          1,056 │ dense_1[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_7 (Dense)           │ (None, 2)              │             66 │ dense_6[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_11 (Dense)          │ (None, 2)              │             66 │ dense_10[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 5,092 (19.89 KB)

 Trainable params: 5,092 (19.89 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
# Train the model
train_test_split(x_df, y_df, random_state=1)

[array([[ 3.70000000e+01,  1.00000000e+00,  1.00000000e+00, ...,
          4.00000000e+00,  1.00000000e+00,  2.00041387e-16],
        [ 2.70000000e+01,  1.00000000e+00,  3.00000000e+00, ...,
          4.00000000e+00,  1.00000000e+00,  2.00041387e-16],
        [ 3.00000000e+01, -3.57639921e-16,  1.20000000e+01, ...,
          1.00000000e+00,  1.00000000e+00,  2.00041387e-16],
        ...,
        [ 4.00000000e+01,  7.00000000e+00,  6.00000000e+00, ...,
          4.00000000e+00,  0.00000000e+00,  1.00000000e+00],
        [ 4.30000000e+01,  1.00000000e+00,  1.60000000e+01, ...,
          4.00000000e+00,  0.00000000e+00,  1.00000000e+00],
        [ 2.40000000e+01, -3.57639921e-16,  1.30000000e+01, ...,
          2.00000000e+00,  1.00000000e+00,  2.00041387e-16]]),
 array([[ 3.70000000e+01, -3.57639921e-16,  1.00000000e+01, ...,
          1.00000000e+00,  1.00000000e+00,  2.00041387e-16],
        [ 1.80000000e+01, -3.57639921e-16,  3.00000000e+00, ...,
          4.00000000e+00,  0.00000000e

In [43]:
from math import e
# Evaluate the model with the testing data
evaluations = model.evaluate(x_df, [Department_test, attrition_test])

ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 1470
'y' sizes: 368, 368


In [ ]:
# Print the accuracy for both department and attrition


Attrition predictions accuracy: 0.7880434989929199
Department predictions accuracy: 0.5


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1.
2.
3.